--TABLE MEMBER 만들기
CREATE TABLE MEMBER (
  ID NUMBER(4) CONSTRAINT MEMBER_PK PRIMARY KEY 
, NAME VARCHAR2(20) 
, EMAIL VARCHAR2(100) 
, HP VARCHAR2(13) 
, REGDATE DATE
);
DROP TABLE MEMBER; 
ROLLBACK;
COMMIT;

SELECT * FROM MEMBER;



--삽입 SEQ_MEMBER.NEXTVAL - 자동 증가
INSERT INTO MEMBER VALUES (SEQ_MEMBER.NEXTVAL,'JJANG051','JJANG051@HANMAIL.NET','010-2582-2242',SYSDATE);


-- SYSTEM 계정에서 해야한느 것--
-- CREATE USER TIS001 IDENTIFIED BY 1234;   생성하기...
-- CREATE ROLE USER_ROLE;   ROLE 생성
-- ROLE 에 부여하기
-->GRANT CONNECT, RESOURCE,CREATE VIEW, CREATE TABLE, CREATE SYNONYM, CREATE SEQUENCE TO USER_ROLE;
-- GRANT USER_ROLE TO TIS001; --> 권한 편하게 넣는 법

DELETE FROM MEMBER
WHERE ID = 1002;
ROLLBACK;

SELECT * FROM MEMBER;
UPDATE MEMBER SET NAME = 'TTTT', EMAIL = 'FSDFDISFLD@LSDIJFL.COM', HP  ='1123124'
WHERE ID = 1003;
ROLLBACK;

SELECT * FROM MEMBER
WHERE ID = 1008;