CREATE TABLE MEMBER(
    NO NUMBER(4) NOT NULL,
    ID VARCHAR2(20) NOT NULL CONSTRAINT MEMBER_PK PRIMARY KEY,
    PASSWORD VARCHAR2(50) NOT NULL,
    NAME VARCHAR2(50) NOT NULL,
    EMAIL VARCHAR2(100) NOT NULL,
    PHONE VARCHAR2(15) NOT NULL,
    ZIPCODE NUMBER(10) NOT NULL,
    ADDRESS VARCHAR2(100) NOT NULL,
    REGDATE DATE
);

SELECT * 
FROM MEMBER
WHERE ID = "test2022";

SELECT *
FROM MEMBER;

DELETE FROM MEMBER
WHERE ID = "test002" AND PASSWORD = "1111";

ROLLBACK;

UPDATE MEMBER SET NAME='둘리', EMAIL='JSDIJ@SIDFLSDJ.COM, PHONE='01022221111', ZIPCODE='33532',ADDRESS='경기도 어느곳'
WHERE ID='HONE001' AND PASSWORD='1234';;

CREATE TABLE NOTICE (
    NO NUMBER(4) NOT NULL CONSTRAINT MOTICE_PK  PRIMARY KEY,
    TITLE VARCHAR2(100),
    CONTENT VARCHAR2(2000),
    REGDATE DATE
);