--테이블 만들기
CREATE TABLE TEMP (
    COL01 VARCHAR2(20),
    COL02 VARCHAR2(20)
    );

SELECT * FROM TEMP; 

--SOCOTT에 있는 TEMP 조회
INSERT INTO SCOTT.TEMP VALUES ('003','SCOTT03 데이터');    

SELECT * FROM SCOTT.TEMP;

--ORCLSTUDY에 있는 TEMP에게 SELECT,INSERT 할수 있는 권한 주기 TO SCOTT에게
--GRANT SELECT ON TEMP TO SCOTT;
--GRANT INSERT ON TEMP TO SCOTT;
GRANT INSERT, SELECT ON TEMP TO SCOTT;