SELECT * FROM DBA_TABLES; -- SYS계정에서만 확인 가능


SELECT * FROM DBA_USERS
WHERE USER_NAME = 'SCOTT';


---GRANT 권한 주어야 하는 것들
GRANT CREATE VIEW TO SCOTT; -- VIEW 권한 설정(SCOTT에게)
GRANT CREATE SYNONYM TO SCOTT; -- SYNONYM동의어 권한
GRANT CREATE PUBLIC SYNONYM TO SCOTT;


-----------------------사용자 ----------------------
--BY 뒤에는 비밀번호
CREATE USER ORCLSTUDY03 IDENTIFIED BY ORACLE; -- SYS계정에서만 가능(DB접속 권한)
--GRANT 권한
GRANT CREATE SESSION TO ORCLSTUDY02; -- CREATE SESSION  권한 주기(접속에 관한 권한)
GRANT RESOURCE, CREATE SESSION, CREATE TABLE TO ORCLSTUDY02;
--RESOURCE, CREATE SESSION, CREATE TABLE 만들 수 있는 권한 주기


--삭제 (사용자를 지우고 싶을때) CASCADE - 접속해제 해주기
DROP USER ORCLSTUDY02 CASCADE;
DROP USER ORCLSTUDY CASCADE;




--ROLE(역할)
--앞으로 ROLESTUDY를 부여 받으면 일일이 부여할 필요 없다
CREATE ROLE ROLESTUDY;
GRANT CONNECT, RESOURCE, CREATE TABLE, CREATE VIEW, CREATE SYNONYM TO ROLESTUDY;


--한번에 권한 주는 법(ROLE(역할) 사용)
CREATE USER NEWORCL IDENTIFIED BY ORACLE;
GRANT ROLESTUDY TO NEWORCL;


-------문제

CREATE USER PREV_HW IDENTIFIED BY ORCL;
GRANT CREATE SESSION TO PREV_HW;




