CREATE TABLE BOARD(
    NO NUMBER(10,0) CONSTRAINT BOARD_PK PRIMARY KEY,
    NAME VARCHAR2(100) NOT NULL,
    SUBJECT VARCHAR2(200) NOT NULL,
    EMAIL VARCHAR2(100) NOT NULL,
    PASSWORD VARCHAR2(100) NOT NULL,
    CONTENTS VARCHAR2(400) NOT NULL,
    REGDATE DATE NOT NULL,
    HIT NUMBER(10) NOT NULL
    );
    
    select*from board;
    
    