DROP TABLE MARIO;
CREATE TABLE MARIO(
    NO NUMBER(4),
    TITLE VARCHAR2(100),
    CONTENTS VARCHAR2(4000),
    LINK VARCHAR2(100),
    BG VARCHAR2(100),
    MARIO_IMG VARCHAR2(100),
    MARIO_REAL_IMG VARCHAR2(100)
    );
    
DESC MARIO;

SELECT * FROM MARIO;
